name: submit_button
description: A flutter animated button customization for forms and login/registration pages.
version: 0.0.4
repository: https://github.com/efikas/submit_button
issue_tracker: https://github.com/efikas/submit_button/issues
homepage: http://efikas.com.ng


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  