name: submit_button
description: Submit button with animation.
version: 0.0.3
repository: https://github.com/efikas/submit_button
issue_tracker: https://github.com/efikas/submit_button/issues
homepage: https://efikas.com.ng


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  